/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EcologyRouteImport } from './routes/ecology'
import { Route as PhosRouteImport } from './routes/phos'
import { Route as EcologyCryptRouteImport } from './routes/ecology_.crypt'
import { Route as EcologyFormRouteImport } from './routes/ecology_.form'
import { Route as EcologyHydrologyRouteImport } from './routes/ecology_.hydrology'
import { Route as EcologyMorphaitherRouteImport } from './routes/ecology_.morphaither'
import { Route as EcologyOssuaryRouteImport } from './routes/ecology_.ossuary'
import { Route as EcologySapRouteImport } from './routes/ecology_.sap'
import { Route as PhosDivisionRouteImport } from './routes/phos_.$division'
import { Route as PhosBrowseRouteImport } from './routes/phos_.browse'
import { Route as PhosPortalRouteImport } from './routes/phos_.portal'
import { Route as PhosToolsRouteImport } from './routes/phos_.tools'
import { Route as PhosDivisionEntryRouteImport } from './routes/phos_.$division_.$entry'
import { Route as PhosToolsAnatomyRouteImport } from './routes/phos_.tools_.anatomy'
import { Route as PhosToolsAtlasRouteImport } from './routes/phos_.tools_.atlas'
import { Route as PhosToolsBeingsRouteImport } from './routes/phos_.tools_.beings'
import { Route as PhosToolsConstellationRouteImport } from './routes/phos_.tools_.constellation'
import { Route as PhosToolsDiagramsRouteImport } from './routes/phos_.tools_.diagrams'
import { Route as PhosToolsFlashingRouteImport } from './routes/phos_.tools_.flashing'
import { Route as PhosToolsSymbolsRouteImport } from './routes/phos_.tools_.symbols'
import { Route as PhosToolsTraceRouteImport } from './routes/phos_.tools_.trace'
import { Route as PhosToolsTraditionsRouteImport } from './routes/phos_.tools_.traditions'
import { Route as PhosBrowseFacetValueRouteImport } from './routes/phos_.browse_.$facet.$value'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EcologyRoute = EcologyRouteImport.update({
  id: '/ecology',
  path: '/ecology',
  getParentRoute: () => rootRouteImport,
} as any)
const PhosRoute = PhosRouteImport.update({
  id: '/phos',
  path: '/phos',
  getParentRoute: () => rootRouteImport,
} as any)
const EcologyCryptRoute = EcologyCryptRouteImport.update({
  id: '/ecology_/crypt',
  path: '/ecology/crypt',
  getParentRoute: () => rootRouteImport,
} as any)
const EcologyFormRoute = EcologyFormRouteImport.update({
  id: '/ecology_/form',
  path: '/ecology/form',
  getParentRoute: () => rootRouteImport,
} as any)
const EcologyHydrologyRoute = EcologyHydrologyRouteImport.update({
  id: '/ecology_/hydrology',
  path: '/ecology/hydrology',
  getParentRoute: () => rootRouteImport,
} as any)
const EcologyMorphaitherRoute = EcologyMorphaitherRouteImport.update({
  id: '/ecology_/morphaither',
  path: '/ecology/morphaither',
  getParentRoute: () => rootRouteImport,
} as any)
const EcologyOssuaryRoute = EcologyOssuaryRouteImport.update({
  id: '/ecology_/ossuary',
  path: '/ecology/ossuary',
  getParentRoute: () => rootRouteImport,
} as any)
const EcologySapRoute = EcologySapRouteImport.update({
  id: '/ecology_/sap',
  path: '/ecology/sap',
  getParentRoute: () => rootRouteImport,
} as any)
const PhosDivisionRoute = PhosDivisionRouteImport.update({
  id: '/phos_/$division',
  path: '/phos/$division',
  getParentRoute: () => rootRouteImport,
} as any)
const PhosBrowseRoute = PhosBrowseRouteImport.update({
  id: '/phos_/browse',
  path: '/phos/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const PhosPortalRoute = PhosPortalRouteImport.update({
  id: '/phos_/portal',
  path: '/phos/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PhosToolsRoute = PhosToolsRouteImport.update({
  id: '/phos_/tools',
  path: '/phos/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const PhosDivisionEntryRoute = PhosDivisionEntryRouteImport.update({
  id: '/phos_/$division_/$entry',
  path: '/phos/$division/$entry',
  getParentRoute: () => rootRouteImport,
} as any)
const PhosToolsAnatomyRoute = PhosToolsAnatomyRouteImport.update({
  id: '/phos_/tools_/anatomy',
  path: '/phos/tools/anatomy',
  getParentRoute: () => rootRouteImport,
} as any)
const PhosToolsAtlasRoute = PhosToolsAtlasRouteImport.update({
  id: '/phos_/tools_/atlas',
  path: '/phos/tools/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const PhosToolsBeingsRoute = PhosToolsBeingsRouteImport.update({
  id: '/phos_/tools_/beings',
  path: '/phos/tools/beings',
  getParentRoute: () => rootRouteImport,
} as any)
const PhosToolsConstellationRoute = PhosToolsConstellationRouteImport.update({
  id: '/phos_/tools_/constellation',
  path: '/phos/tools/constellation',
  getParentRoute: () => rootRouteImport,
} as any)
const PhosToolsDiagramsRoute = PhosToolsDiagramsRouteImport.update({
  id: '/phos_/tools_/diagrams',
  path: '/phos/tools/diagrams',
  getParentRoute: () => rootRouteImport,
} as any)
const PhosToolsFlashingRoute = PhosToolsFlashingRouteImport.update({
  id: '/phos_/tools_/flashing',
  path: '/phos/tools/flashing',
  getParentRoute: () => rootRouteImport,
} as any)
const PhosToolsSymbolsRoute = PhosToolsSymbolsRouteImport.update({
  id: '/phos_/tools_/symbols',
  path: '/phos/tools/symbols',
  getParentRoute: () => rootRouteImport,
} as any)
const PhosToolsTraceRoute = PhosToolsTraceRouteImport.update({
  id: '/phos_/tools_/trace',
  path: '/phos/tools/trace',
  getParentRoute: () => rootRouteImport,
} as any)
const PhosToolsTraditionsRoute = PhosToolsTraditionsRouteImport.update({
  id: '/phos_/tools_/traditions',
  path: '/phos/tools/traditions',
  getParentRoute: () => rootRouteImport,
} as any)
const PhosBrowseFacetValueRoute = PhosBrowseFacetValueRouteImport.update({
  id: '/phos_/browse_/$facet/$value',
  path: '/phos/browse/$facet/$value',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ecology': typeof EcologyRoute
  '/phos': typeof PhosRoute
  '/ecology/crypt': typeof EcologyCryptRoute
  '/ecology/form': typeof EcologyFormRoute
  '/ecology/hydrology': typeof EcologyHydrologyRoute
  '/ecology/morphaither': typeof EcologyMorphaitherRoute
  '/ecology/ossuary': typeof EcologyOssuaryRoute
  '/ecology/sap': typeof EcologySapRoute
  '/phos/$division': typeof PhosDivisionRoute
  '/phos/browse': typeof PhosBrowseRoute
  '/phos/portal': typeof PhosPortalRoute
  '/phos/tools': typeof PhosToolsRoute
  '/phos/$division/$entry': typeof PhosDivisionEntryRoute
  '/phos/tools/anatomy': typeof PhosToolsAnatomyRoute
  '/phos/tools/atlas': typeof PhosToolsAtlasRoute
  '/phos/tools/beings': typeof PhosToolsBeingsRoute
  '/phos/tools/constellation': typeof PhosToolsConstellationRoute
  '/phos/tools/diagrams': typeof PhosToolsDiagramsRoute
  '/phos/tools/flashing': typeof PhosToolsFlashingRoute
  '/phos/tools/symbols': typeof PhosToolsSymbolsRoute
  '/phos/tools/trace': typeof PhosToolsTraceRoute
  '/phos/tools/traditions': typeof PhosToolsTraditionsRoute
  '/phos/browse/$facet/$value': typeof PhosBrowseFacetValueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ecology': typeof EcologyRoute
  '/phos': typeof PhosRoute
  '/ecology/crypt': typeof EcologyCryptRoute
  '/ecology/form': typeof EcologyFormRoute
  '/ecology/hydrology': typeof EcologyHydrologyRoute
  '/ecology/morphaither': typeof EcologyMorphaitherRoute
  '/ecology/ossuary': typeof EcologyOssuaryRoute
  '/ecology/sap': typeof EcologySapRoute
  '/phos/$division': typeof PhosDivisionRoute
  '/phos/browse': typeof PhosBrowseRoute
  '/phos/portal': typeof PhosPortalRoute
  '/phos/tools': typeof PhosToolsRoute
  '/phos/$division/$entry': typeof PhosDivisionEntryRoute
  '/phos/tools/anatomy': typeof PhosToolsAnatomyRoute
  '/phos/tools/atlas': typeof PhosToolsAtlasRoute
  '/phos/tools/beings': typeof PhosToolsBeingsRoute
  '/phos/tools/constellation': typeof PhosToolsConstellationRoute
  '/phos/tools/diagrams': typeof PhosToolsDiagramsRoute
  '/phos/tools/flashing': typeof PhosToolsFlashingRoute
  '/phos/tools/symbols': typeof PhosToolsSymbolsRoute
  '/phos/tools/trace': typeof PhosToolsTraceRoute
  '/phos/tools/traditions': typeof PhosToolsTraditionsRoute
  '/phos/browse/$facet/$value': typeof PhosBrowseFacetValueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ecology': typeof EcologyRoute
  '/phos': typeof PhosRoute
  '/ecology_/crypt': typeof EcologyCryptRoute
  '/ecology_/form': typeof EcologyFormRoute
  '/ecology_/hydrology': typeof EcologyHydrologyRoute
  '/ecology_/morphaither': typeof EcologyMorphaitherRoute
  '/ecology_/ossuary': typeof EcologyOssuaryRoute
  '/ecology_/sap': typeof EcologySapRoute
  '/phos_/$division': typeof PhosDivisionRoute
  '/phos_/browse': typeof PhosBrowseRoute
  '/phos_/portal': typeof PhosPortalRoute
  '/phos_/tools': typeof PhosToolsRoute
  '/phos_/$division_/$entry': typeof PhosDivisionEntryRoute
  '/phos_/tools_/anatomy': typeof PhosToolsAnatomyRoute
  '/phos_/tools_/atlas': typeof PhosToolsAtlasRoute
  '/phos_/tools_/beings': typeof PhosToolsBeingsRoute
  '/phos_/tools_/constellation': typeof PhosToolsConstellationRoute
  '/phos_/tools_/diagrams': typeof PhosToolsDiagramsRoute
  '/phos_/tools_/flashing': typeof PhosToolsFlashingRoute
  '/phos_/tools_/symbols': typeof PhosToolsSymbolsRoute
  '/phos_/tools_/trace': typeof PhosToolsTraceRoute
  '/phos_/tools_/traditions': typeof PhosToolsTraditionsRoute
  '/phos_/browse_/$facet/$value': typeof PhosBrowseFacetValueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ecology'
    | '/phos'
    | '/ecology/crypt'
    | '/ecology/form'
    | '/ecology/hydrology'
    | '/ecology/morphaither'
    | '/ecology/ossuary'
    | '/ecology/sap'
    | '/phos/$division'
    | '/phos/browse'
    | '/phos/portal'
    | '/phos/tools'
    | '/phos/$division/$entry'
    | '/phos/tools/anatomy'
    | '/phos/tools/atlas'
    | '/phos/tools/beings'
    | '/phos/tools/constellation'
    | '/phos/tools/diagrams'
    | '/phos/tools/flashing'
    | '/phos/tools/symbols'
    | '/phos/tools/trace'
    | '/phos/tools/traditions'
    | '/phos/browse/$facet/$value'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ecology'
    | '/phos'
    | '/ecology/crypt'
    | '/ecology/form'
    | '/ecology/hydrology'
    | '/ecology/morphaither'
    | '/ecology/ossuary'
    | '/ecology/sap'
    | '/phos/$division'
    | '/phos/browse'
    | '/phos/portal'
    | '/phos/tools'
    | '/phos/$division/$entry'
    | '/phos/tools/anatomy'
    | '/phos/tools/atlas'
    | '/phos/tools/beings'
    | '/phos/tools/constellation'
    | '/phos/tools/diagrams'
    | '/phos/tools/flashing'
    | '/phos/tools/symbols'
    | '/phos/tools/trace'
    | '/phos/tools/traditions'
    | '/phos/browse/$facet/$value'
  id:
    | '__root__'
    | '/'
    | '/ecology'
    | '/phos'
    | '/ecology_/crypt'
    | '/ecology_/form'
    | '/ecology_/hydrology'
    | '/ecology_/morphaither'
    | '/ecology_/ossuary'
    | '/ecology_/sap'
    | '/phos_/$division'
    | '/phos_/browse'
    | '/phos_/portal'
    | '/phos_/tools'
    | '/phos_/$division_/$entry'
    | '/phos_/tools_/anatomy'
    | '/phos_/tools_/atlas'
    | '/phos_/tools_/beings'
    | '/phos_/tools_/constellation'
    | '/phos_/tools_/diagrams'
    | '/phos_/tools_/flashing'
    | '/phos_/tools_/symbols'
    | '/phos_/tools_/trace'
    | '/phos_/tools_/traditions'
    | '/phos_/browse_/$facet/$value'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EcologyRoute: typeof EcologyRoute
  PhosRoute: typeof PhosRoute
  EcologyCryptRoute: typeof EcologyCryptRoute
  EcologyFormRoute: typeof EcologyFormRoute
  EcologyHydrologyRoute: typeof EcologyHydrologyRoute
  EcologyMorphaitherRoute: typeof EcologyMorphaitherRoute
  EcologyOssuaryRoute: typeof EcologyOssuaryRoute
  EcologySapRoute: typeof EcologySapRoute
  PhosDivisionRoute: typeof PhosDivisionRoute
  PhosBrowseRoute: typeof PhosBrowseRoute
  PhosPortalRoute: typeof PhosPortalRoute
  PhosToolsRoute: typeof PhosToolsRoute
  PhosDivisionEntryRoute: typeof PhosDivisionEntryRoute
  PhosToolsAnatomyRoute: typeof PhosToolsAnatomyRoute
  PhosToolsAtlasRoute: typeof PhosToolsAtlasRoute
  PhosToolsBeingsRoute: typeof PhosToolsBeingsRoute
  PhosToolsConstellationRoute: typeof PhosToolsConstellationRoute
  PhosToolsDiagramsRoute: typeof PhosToolsDiagramsRoute
  PhosToolsFlashingRoute: typeof PhosToolsFlashingRoute
  PhosToolsSymbolsRoute: typeof PhosToolsSymbolsRoute
  PhosToolsTraceRoute: typeof PhosToolsTraceRoute
  PhosToolsTraditionsRoute: typeof PhosToolsTraditionsRoute
  PhosBrowseFacetValueRoute: typeof PhosBrowseFacetValueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecology': {
      id: '/ecology'
      path: '/ecology'
      fullPath: '/ecology'
      preLoaderRoute: typeof EcologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phos': {
      id: '/phos'
      path: '/phos'
      fullPath: '/phos'
      preLoaderRoute: typeof PhosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecology_/crypt': {
      id: '/ecology_/crypt'
      path: '/ecology/crypt'
      fullPath: '/ecology/crypt'
      preLoaderRoute: typeof EcologyCryptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecology_/form': {
      id: '/ecology_/form'
      path: '/ecology/form'
      fullPath: '/ecology/form'
      preLoaderRoute: typeof EcologyFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecology_/hydrology': {
      id: '/ecology_/hydrology'
      path: '/ecology/hydrology'
      fullPath: '/ecology/hydrology'
      preLoaderRoute: typeof EcologyHydrologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecology_/morphaither': {
      id: '/ecology_/morphaither'
      path: '/ecology/morphaither'
      fullPath: '/ecology/morphaither'
      preLoaderRoute: typeof EcologyMorphaitherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecology_/ossuary': {
      id: '/ecology_/ossuary'
      path: '/ecology/ossuary'
      fullPath: '/ecology/ossuary'
      preLoaderRoute: typeof EcologyOssuaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecology_/sap': {
      id: '/ecology_/sap'
      path: '/ecology/sap'
      fullPath: '/ecology/sap'
      preLoaderRoute: typeof EcologySapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phos_/$division': {
      id: '/phos_/$division'
      path: '/phos/$division'
      fullPath: '/phos/$division'
      preLoaderRoute: typeof PhosDivisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phos_/browse': {
      id: '/phos_/browse'
      path: '/phos/browse'
      fullPath: '/phos/browse'
      preLoaderRoute: typeof PhosBrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phos_/portal': {
      id: '/phos_/portal'
      path: '/phos/portal'
      fullPath: '/phos/portal'
      preLoaderRoute: typeof PhosPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phos_/tools': {
      id: '/phos_/tools'
      path: '/phos/tools'
      fullPath: '/phos/tools'
      preLoaderRoute: typeof PhosToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phos_/$division_/$entry': {
      id: '/phos_/$division_/$entry'
      path: '/phos/$division/$entry'
      fullPath: '/phos/$division/$entry'
      preLoaderRoute: typeof PhosDivisionEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phos_/tools_/anatomy': {
      id: '/phos_/tools_/anatomy'
      path: '/phos/tools/anatomy'
      fullPath: '/phos/tools/anatomy'
      preLoaderRoute: typeof PhosToolsAnatomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phos_/tools_/atlas': {
      id: '/phos_/tools_/atlas'
      path: '/phos/tools/atlas'
      fullPath: '/phos/tools/atlas'
      preLoaderRoute: typeof PhosToolsAtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phos_/tools_/beings': {
      id: '/phos_/tools_/beings'
      path: '/phos/tools/beings'
      fullPath: '/phos/tools/beings'
      preLoaderRoute: typeof PhosToolsBeingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phos_/tools_/constellation': {
      id: '/phos_/tools_/constellation'
      path: '/phos/tools/constellation'
      fullPath: '/phos/tools/constellation'
      preLoaderRoute: typeof PhosToolsConstellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phos_/tools_/diagrams': {
      id: '/phos_/tools_/diagrams'
      path: '/phos/tools/diagrams'
      fullPath: '/phos/tools/diagrams'
      preLoaderRoute: typeof PhosToolsDiagramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phos_/tools_/flashing': {
      id: '/phos_/tools_/flashing'
      path: '/phos/tools/flashing'
      fullPath: '/phos/tools/flashing'
      preLoaderRoute: typeof PhosToolsFlashingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phos_/tools_/symbols': {
      id: '/phos_/tools_/symbols'
      path: '/phos/tools/symbols'
      fullPath: '/phos/tools/symbols'
      preLoaderRoute: typeof PhosToolsSymbolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phos_/tools_/trace': {
      id: '/phos_/tools_/trace'
      path: '/phos/tools/trace'
      fullPath: '/phos/tools/trace'
      preLoaderRoute: typeof PhosToolsTraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phos_/tools_/traditions': {
      id: '/phos_/tools_/traditions'
      path: '/phos/tools/traditions'
      fullPath: '/phos/tools/traditions'
      preLoaderRoute: typeof PhosToolsTraditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phos_/browse_/$facet/$value': {
      id: '/phos_/browse_/$facet/$value'
      path: '/phos/browse/$facet/$value'
      fullPath: '/phos/browse/$facet/$value'
      preLoaderRoute: typeof PhosBrowseFacetValueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EcologyRoute: EcologyRoute,
  PhosRoute: PhosRoute,
  EcologyCryptRoute: EcologyCryptRoute,
  EcologyFormRoute: EcologyFormRoute,
  EcologyHydrologyRoute: EcologyHydrologyRoute,
  EcologyMorphaitherRoute: EcologyMorphaitherRoute,
  EcologyOssuaryRoute: EcologyOssuaryRoute,
  EcologySapRoute: EcologySapRoute,
  PhosDivisionRoute: PhosDivisionRoute,
  PhosBrowseRoute: PhosBrowseRoute,
  PhosPortalRoute: PhosPortalRoute,
  PhosToolsRoute: PhosToolsRoute,
  PhosDivisionEntryRoute: PhosDivisionEntryRoute,
  PhosToolsAnatomyRoute: PhosToolsAnatomyRoute,
  PhosToolsAtlasRoute: PhosToolsAtlasRoute,
  PhosToolsBeingsRoute: PhosToolsBeingsRoute,
  PhosToolsConstellationRoute: PhosToolsConstellationRoute,
  PhosToolsDiagramsRoute: PhosToolsDiagramsRoute,
  PhosToolsFlashingRoute: PhosToolsFlashingRoute,
  PhosToolsSymbolsRoute: PhosToolsSymbolsRoute,
  PhosToolsTraceRoute: PhosToolsTraceRoute,
  PhosToolsTraditionsRoute: PhosToolsTraditionsRoute,
  PhosBrowseFacetValueRoute: PhosBrowseFacetValueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
